language: python

services:
  - mongodb

python:
  - 2.7
#  - 3.4

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH
  - export FS_HOST=localhost
  - export FS_DATABASE=test
  - mkdir -p /home/travis/.config/filestore
  - 'echo ''port: 27017'' > /home/travis/.config/filestore/connection.yml'

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda config --set always_yes true
  - conda update conda --yes
  - conda config --add channels lightsource2
  - conda create -n testenv pip pytest python=$TRAVIS_PYTHON_VERSION pymongo six pyyaml numpy pandas jinja2 humanize doct filestore nose
  - source activate testenv
  - pip install coveralls mongoengine ase
  - 'pip install https://github.com/CJ-Wright/pyIID/zipball/master#egg=pyIID'
  - python setup.py install
  - pip install coveralls


script:
  - python run_tests.py

after_script:
  coveralls
